{
  "artifacts": [],
  "command": "main",
  "experiment": {
    "base_dir": "/home/lgrootde/Generative-re-tests",
    "dependencies": [
      "datasets==2.17.1",
      "evaluate==0.4.1",
      "numpy==1.26.4",
      "sacred==0.8.5",
      "torch==2.2.1",
      "transformers==4.38.1",
      "wasabi==1.1.2"
    ],
    "mainfile": "run.py",
    "name": "generative_re",
    "repositories": [
      {
        "commit": "c45650c02ab9357d655637ef1711d9562e5cf4ce",
        "dirty": true,
        "url": "https://github.com/ontox-hu/Generative-re-tests"
      }
    ],
    "sources": [
      [
        "run.py",
        "_sources/run_4c66c4413d792bfeb65515fd0d80bf68.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/sacred/config/captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/run.py\", line 604, in main\n    trainer.train()\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/transformers/trainer.py\", line 1624, in train\n    return inner_training_loop(\n           ^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/transformers/trainer.py\", line 1776, in _inner_training_loop\n    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/lgrootde/Generative-re-tests/venv/lib/python3.12/site-packages/accelerate/accelerator.py\", line 1179, in prepare\n    raise ValueError(\n",
    "ValueError: You can't train a model that has been loaded with `device_map='auto'` in any distributed mode. Please rerun your script specifying `--num_processes=1` or by launching with `python {{myscript.py}}`.\n"
  ],
  "heartbeat": "2024-04-23T14:01:27.102392",
  "host": {
    "ENV": {},
    "cpu": "AMD EPYC 7V13 64-Core Processor",
    "gpus": {
      "driver_version": "545.23.08",
      "gpus": [
        {
          "model": "NVIDIA A100 80GB PCIe",
          "persistence_mode": false,
          "total_memory": 81920
        },
        {
          "model": "NVIDIA A100 80GB PCIe",
          "persistence_mode": false,
          "total_memory": 81920
        },
        {
          "model": "NVIDIA A100 80GB PCIe",
          "persistence_mode": false,
          "total_memory": 81920
        },
        {
          "model": "NVIDIA A100 80GB PCIe",
          "persistence_mode": false,
          "total_memory": 81920
        }
      ]
    },
    "hostname": "genllmre",
    "os": [
      "Linux",
      "Linux-5.15.0-1061-azure-x86_64-with-glibc2.31"
    ],
    "python_version": "3.12.2"
  },
  "meta": {
    "command": "main",
    "config_updates": {},
    "named_configs": [
      "config/config_T5-11b_cdr.yaml"
    ],
    "options": {
      "--beat-interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--id": null,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print-config": false,
      "--priority": null,
      "--queue": false,
      "--s3": null,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [
        "config/config_T5-11b_cdr.yaml"
      ],
      "help": false,
      "with": true
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2024-04-23T12:51:16.045002",
  "status": "FAILED",
  "stop_time": "2024-04-23T14:01:27.103318"
}